name: Test 1 Minute Monitor

on:
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Test polling setiap 1 menit
        run: |
          echo "=== MONITOR DIMULAI ==="
          date

          for i in {1..5}
          do
            echo ""
            echo "===== CHECK $i ====="
            date
            echo "Pengecekan ke-$i berhasil."

            if [ $i -lt 5 ]; then
              echo "Menunggu 60 detik..."
              sleep 60
            fi
          done

          echo ""
          echo "=== MONITOR SELESAI ==="
          date
